# Generated by Django 5.2.7 on 2025-10-14 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('btc_wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='BTC Wallet Address')),
                ('ethereum_wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ethereum Wallet Address')),
                ('usdt_wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='USDT Wallet Address')),
                ('litecoin_wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Litecoin Wallet Address')),
                ('tron_wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tron Wallet Address')),
                ('btc_balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('ethereum_balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('usdt_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('litecoin_balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('tron_balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='kyc_documents/')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'custom_users',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('TRADE', 'Trade Execution'), ('DEPOSIT', 'Funds Deposit'), ('WITHDRAWAL', 'Funds Withdrawal'), ('PROFILE_UPDATE', 'Profile Update')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
