# Generated by Django 5.2.7 on 2025-10-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venex_app', '0002_remove_transaction_get_cryptocurrency_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='get_cryptocurrency_display',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether (USDT)'), ('LTC', 'Litecoin'), ('TRX', 'Tron')], default='', max_length=10),
        ),
    ]
