# Generated by Django 5.2.7 on 2025-10-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venex_app', '0003_remove_portfolio_currency_type_alter_portfolio_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cryptocurrency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='venex_app.cryptocurrency'),
        ),
    ]
