# Generated by Django 5.2.7 on 2025-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venex_app', '0004_alter_cryptocurrency_get_cryptocurrency_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='get_cryptocurrency_display',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], default='', max_length=10),
        ),
    ]
