# Generated by Django 5.2.7 on 2025-10-24 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venex_app', '0005_alter_cryptocurrency_get_cryptocurrency_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='venex_app.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Portfolio History',
                'db_table': 'portfolio_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('average_buy_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('unrealized_pl_percentage', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('allocation_percentage', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venex_app.cryptocurrency')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='venex_app.portfolio')),
            ],
            options={
                'db_table': 'portfolio_holdings',
                'unique_together': {('portfolio', 'cryptocurrency')},
            },
        ),
    ]
