# Generated by Django 5.2.7 on 2025-10-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venex_app', '0007_buy_sell_wallet_customuser_currency_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='profit_loss_percentage',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
