# Generated by Django 5.2.7 on 2025-11-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venex_app', '0008_update_profit_loss_percentage_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='BTC Wallet Address')),
                ('ethereum_wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ethereum Wallet Address')),
                ('usdt_wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='USDT Wallet Address')),
                ('litecoin_wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Litecoin Wallet Address')),
                ('tron_wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tron Wallet Address')),
            ],
        ),
        migrations.DeleteModel(
            name='Buy_Sell_Wallet',
        ),
    ]
