# Generated by Django 5.2.7 on 2025-11-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venex_app', '0009_admin_wallet_delete_buy_sell_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(choices=[('USD', 'America United States Dollars – USD'), ('AFN', 'Afghanistan Afghanis – AFN'), ('ALL', 'Albania Leke – ALL'), ('DZD', 'Algeria Dinars – DZD'), ('ARS', 'Argentina Pesos – ARS'), ('AUD', 'Australia Dollars – AUD'), ('ATS', 'Austria Schillings – ATS'), ('BSD', 'Bahamas Dollars – BSD'), ('BHD', 'Bahrain Dinars – BHD'), ('BDT', 'Bangladesh Taka – BDT'), ('BBD', 'Barbados Dollars – BBD'), ('BEF', 'Belgium Francs – BEF'), ('BMD', 'Bermuda Dollars – BMD'), ('BRL', 'Brazil Reais – BRL'), ('BGN', 'Bulgaria Leva – BGN'), ('CAD', 'Canada Dollars – CAD'), ('XOF', 'CFA BCEAO Francs – XOF'), ('XAF', 'CFA BEAC Francs – XAF'), ('CLP', 'Chile Pesos – CLP'), ('CNY', 'China Yuan Renminbi – CNY'), ('CNY', 'RMB (China Yuan Renminbi), – CNY'), ('COP', 'Colombia Pesos – COP'), ('XPF', 'CFP Francs – XPF'), ('CRC', 'Costa Rica Colones – CRC'), ('HRK', 'Croatia Kuna – HRK'), ('CYP', 'Cyprus Pounds – CYP'), ('CZK', 'Czech Republic Koruny – CZK'), ('DKK', 'Denmark Kroner – DKK'), ('DEM', 'Deutsche (Germany), Marks – DEM'), ('DOP', 'Dominican Republic Pesos – DOP'), ('NLG', 'Dutch (Netherlands), Guilders – NLG'), ('XCD', 'Eastern Caribbean Dollars – XCD'), ('EGP', 'Egypt Pounds – EGP'), ('EEK', 'Estonia Krooni – EEK'), ('EUR', 'Euro – EUR'), ('FJD', 'Fiji Dollars – FJD'), ('FIM', 'Finland Markkaa – FIM'), ('FRF', 'France Francs – FRF'), ('DEM', 'Germany Deutsche Marks – DEM'), ('XAU', 'Gold Ounces – XAU'), ('GRD', 'Greece Drachmae – GRD'), ('GTQ', 'Guatemalan Quetzal – GTQ'), ('NLG', 'Holland (Netherlands), Guilders – NLG'), ('HKD', 'Hong Kong Dollars – HKD'), ('HUF', 'Hungary Forint – HUF'), ('ISK', 'Iceland Kronur – ISK'), ('XDR', 'IMF Special Drawing Right – XDR'), ('INR', 'India Rupees – INR'), ('IDR', 'Indonesia Rupiahs – IDR'), ('IRR', 'Iran Rials – IRR'), ('IQD', 'Iraq Dinars – IQD'), ('IEP', 'Ireland Pounds – IEP'), ('ILS', 'Israel New Shekels – ILS'), ('ITL', 'Italy Lire – ITL'), ('JMD', 'Jamaica Dollars – JMD'), ('JPY', 'Japan Yen – JPY'), ('JOD', 'Jordan Dinars – JOD'), ('KES', 'Kenya Shillings – KES'), ('KRW', 'Korea (South), Won – KRW'), ('KWD', 'Kuwait Dinars – KWD'), ('LBP', 'Lebanon Pounds – LBP'), ('LUF', 'Luxembourg Francs – LUF'), ('MYR', 'Malaysia Ringgits – MYR'), ('MTL', 'Malta Liri – MTL'), ('MUR', 'Mauritius Rupees – MUR'), ('MXN', 'Mexico Pesos – MXN'), ('MAD', 'Morocco Dirhams – MAD'), ('NLG', 'Netherlands Guilders – NLG'), ('NZD', 'New Zealand Dollars – NZD'), ('NGN', 'Nigeria Naira – NGN'), ('NOK', 'Norway Kroner – NOK'), ('OMR', 'Oman Rials – OMR'), ('PKR', 'Pakistan Rupees – PKR'), ('XPD', 'Palladium Ounces – XPD'), ('PEN', 'Peru Nuevos Soles – PEN'), ('PHP', 'Philippines Pesos – PHP'), ('XPT', 'Platinum Ounces – XPT'), ('PLN', 'Poland Zlotych – PLN'), ('PTE', 'Portugal Escudos – PTE'), ('QAR', 'Qatar Riyals – QAR'), ('RON', 'Romania New Lei – RON'), ('ROL', 'Romania Lei – ROL'), ('RUB', 'Russia Rubles – RUB'), ('SAR', 'Saudi Arabia Riyals – SAR'), ('XAG', 'Silver Ounces – XAG'), ('SGD', 'Singapore Dollars – SGD'), ('SKK', 'Slovakia Koruny – SKK'), ('SIT', 'Slovenia Tolars – SIT'), ('ZAR', 'South Africa Rand – ZAR'), ('KRW', 'South Korea Won – KRW'), ('ESP', 'Spain Pesetas – ESP'), ('SDD', 'Sudan Dinars – SDD'), ('SEK', 'Sweden Kronor – SEK'), ('CHF', 'Switzerland Francs – CHF'), ('TWD', 'Taiwan New Dollars – TWD'), ('THB', 'Thailand Baht – THB'), ('TTD', 'Trinidad and Tobago Dollars – TTD'), ('TND', 'Tunisia Dinars – TND'), ('TRY', 'Turkey New Lira – TRY'), ('AED', 'United Arab Emirates Dirhams – AED'), ('GBP', 'United Kingdom Pounds – GBP'), ('USD', 'United States Dollars – USD'), ('VEB', 'Venezuela Bolivares – VEB'), ('VND', 'Vietnam Dong – VND'), ('ZMK', 'Zambia Kwacha – ZMK')], default='USD', max_length=97)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Number')),
                ('routing_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Routing Number')),
                ('swift_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='SWIFT Code')),
                ('iban', models.CharField(blank=True, max_length=255, null=True, verbose_name='IBAN')),
            ],
        ),
    ]
